### ISSUE TITLE
Change GH action to install minimally

### ISSUE THREAD

**Issue by albireox** [sdss/sdssdb#31]
@havok2063 

The GitHub action is quite useful, it caught a syntax error nicely. It does build the package as

```
pip install .[all,dev]
```

I wonder if we should just use `pip install .` since that's how most people will install it. In general we should have some tests in place to make sure that if people install sdssdb without the extras at least the basic functionality works and there are no import errors.

**Comment by havok2063** [comment]
I think switching it to `pip install .` sounds reasonable to me.  I originally had it as `.[all,dev]` because for other packages I also run the tests with `pytest`, and I just copied the file.  Since we can't run the tests without some additional setup, we can probably remove the extras.  I agree on having some sanity checks for testing a vanilla install without extras.  

Yeah I'm starting to enjoy these Actions.  I've been playing around with them in some other repos.  I have ones for building Sphinx docs and deploying to PyPi upon a new Github Release.
